name: csm_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/aimldesk_icon.png
    - assets/logo/aimldesk_splash_screen.png

# ✅ Moved OUTSIDE of flutter block!
flutter_launcher_icons:
  image_path: "assets/icons/aimldesk_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1565C0"
  image: assets/logo/aimldesk_splash_screen.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
